openapi: 3.0.3
info:
  title: keiba api
  description: keiba api
  version: 1.0.0
servers:
  - url: http://example.com
    description: example1
paths:
  /users/{userId}/:
    $ref: ./paths/UserDetail.yml
components:
  schemas:
    SystemError:
      $ref: ./schemas/errors/SystemError.yml
    UserDetailResponse:
      $ref: ./schemas/responses/UserDetail.yml
